Downgrade pytest to 4.6.5 that play nicely with pypy3
Pytest > 4.6.5 introduce error like
`AttributeError: module 'faulthandler' has no attribute 'disable'`